### ISSUE TITLE
Cannot convert undefined or null to object while testing with Jest

### ISSUE THREAD

**Issue by TijsM** [nandorojo/moti#94]
When running our Expo project we're not having any issues. but when we're running our Jest tests, they fail with the message: 
 ```
  TypeError: Cannot convert undefined or null to object at Function.values (<anonymous>)
```
Trace: 
``` 
      at useAnimatedStyle (node_modules/react-native-reanimated/lib/reanimated2/Hooks.js:332:27)
      at useMapAnimateToStyle (node_modules/@motify/core/lib/commonjs/use-map-animate-to-style.ts:235:17)
      at Moti (node_modules/@motify/core/lib/commonjs/motify.tsx:47:26)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8038:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10015:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
```

Currently, we're only using Moti in one place: 
I created this simplified version

```
import React, { useState } from 'react'
import { useAnimationState, TransitionConfig } from '@motify/core'
import { Pressable } from 'react-native'
import { View as MotiView } from 'moti'

function useOnPressVariant() {
  return useAnimationState({
    from: {
      opacity: 1,
      scale: 0.95,
    },
    to: {
      opacity: 1,
      scale: 1,
    },
  })
}

const onPressVariantDuration = 100

const onPressTransition: TransitionConfig = {
  type: 'timing',
  duration: onPressVariantDuration,
}

export default function TabBarIcon() {
  const [isPressed, setIsPressed] = useState(false)

  const onNavPressAnimation = useOnPressVariant()

  const handleAnimtion = () => {
    onNavPressAnimation.transitionTo(state => {
      if (state === 'from') {
        return 'to'
      } else {
        return 'from'
      }
    })
  }

  return (
    <Pressable
      onPress={() => {
        // do some navigation
      }}
      onPressIn={() => {
        setIsPressed(true)
        handleAnimtion()
      }}
      onPressOut={() => {
        setIsPressed(false)
        handleAnimtion()
      }}
    >
      <MotiView transition={onPressTransition} state={onNavPressAnimation}>
        {/* some basic jsx */}
      </MotiView>
    </Pressable>
  )
}
```

**Comment by TijsM** [comment]
@nandorojo After trying different approaches, we ended up with this:


First we mocked reanimated:
```
global.__reanimatedWorkletInit = function (worklet) {
  worklet.__worklet = true
}

jest.mock('react-native-reanimated', () =>
  jest.requireActual('react-native-reanimated/mock')
)
```

but for some reason, not all methods are in the mock that reanimated provides, so we extended the mock provided by reanimated:
```
global.__reanimatedWorkletInit = function (worklet) {
  worklet.__worklet = true
}

jest.mock('react-native-reanimated', () => ({
  ...jest.requireActual('react-native-reanimated/mock'),
  makeMutable: f => f,
  useWorkletCallback: f => f,
  useAnimatedProps: style => style,
}))
```

At this point, the Moti issues were gone 🥳 

But unfortunately, we are also using [gorhom/react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet) which had some issues with the mock implementation of reanimated.

We fixed this by also mocking  [gorhom/react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet):

```
const React = require('react')

const BottomSheetModalProvider = ({ children }) => {
  return children
}
const BottomSheetBackdrop = () => {}

class BottomSheetModal extends React.Component {
  close() {}

  present() {}

  render() {
    return this.props.children
  }
}

module.exports = {
  BottomSheetScrollView: props => {
    return props.children
  },
  BottomSheetModalProvider,
  BottomSheetModal,
  BottomSheetBackdrop,
}
```

**Comment by nandorojo** [comment]
Thanks for sharing!
